import * as Knex from 'knex'
import { TABLES } from '../glossary/schema'

export async function seed (knex: Knex): Promise<any> {
  /**
   * Tracers
   */
  await knex('table_row').insert([
    {
      id: 'c6e48b1d-d53a-46cf-bc74-7c81870900f4',
      text: '300FBF',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '300FBF',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '300FBF',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS
      })
    }, {
      id: '61074bd7-c224-4d7b-99a1-5cecfbd23728',
      text: '314AA5',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '314AA5',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '314AA5',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_WORKING
      })
    }, {
      id: 'd8cf9222-9fd6-406d-8b90-1b443e89aa7c',
      text: '314A6A',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '314A6A',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '314A6A',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS
      })
    }, {
      id: '769152a2-ff39-4186-892e-2fdd111e012b',
      text: '314C05',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '314C05',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '314C05',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_STOLEN,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: '26/08/2020'
      })
    }, {
      id: '3532ef04-195f-4584-82f0-6b4fbba14893',
      text: '315302',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '315302',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '315302',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'bdcac9b3-ebf3-4bfa-bfef-e19dd00b0850',
      text: '314B6E',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '314B6E',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '314B6E',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'd8e70a40-841c-4918-907f-48ae0b61cc58',
      text: '314BE4',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '314BE4',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '314BE4',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'd4a61f7b-94c9-41b3-b142-f6f10c123141',
      text: '315258',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '315258',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '315258',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: '27d35c5b-19fe-4d5f-84d6-30e3803933af',
      text: '3152A1',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '3152A1',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '3152A1',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: '54ddfbce-975d-4f7c-84c8-5a318b34dd08',
      text: '31537F',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '31537F',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '31537F',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: '5d2049d0-5455-4b1b-bac7-071a04602e99',
      text: '3151DE',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '3151DE',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '3151DE',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'c12049ee-56bb-4466-b0b5-845ea9185b69',
      text: '3152F0',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '3152F0',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '3152F0',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: '873db4c8-495f-4f4a-8e26-844526c6d452',
      text: '314C43',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '314C43',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '314C43',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'f2126760-42d8-43d6-9e02-e35b81d8d49e',
      text: '315048',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '315048',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '315048',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'a5ac0bba-bb6d-43dd-a7f5-027144df0386',
      text: '315330',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '315330',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '315330',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'abbda7b6-0094-4069-94d7-64521e7eb4f4',
      text: '31537B',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '31537B',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '31537B',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: '9f13fe09-908f-4bd5-8891-0ac808c88187',
      text: '3153B4',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '3153B4',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '3153B4',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'a92715f6-1108-458d-9dd1-2dfdeff12906',
      text: '315240',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '315240',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '315240',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: 'd111a991-11c6-4f07-bb48-59a6d7855981',
      text: '314B15',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '314B15',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '314B15',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, {
      id: '4506c2c9-90a8-4611-a8e7-bc1e402e5e51',
      text: '314B1C',
      table_id: TABLES.MORIO_TRACER.ID,
      data: JSON.stringify({
        [TABLES.MORIO_TRACER.COLUMNS.REF]: '314B1C',
        [TABLES.MORIO_TRACER.COLUMNS.SIGFOX_ID]: '314B1C',
        [TABLES.MORIO_TRACER.COLUMNS.STATUS]: TABLES.MORIO_TRACER.DATA.STATUS_INPROGRESS,
        [TABLES.MORIO_TRACER.COLUMNS.DATE_BEGIN]: null
      })
    }, ])

}
