image: "node:lts-alpine"

pages:
  variables:
    BASE_URL: '/lck-docs/'
  script:
    - npm ci
    - npm run build
    - mv docs/.vitepress/dist public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
