image: node:lts

stages:
  - storybook
  - lint-tests
  - build
  - deploy

.build_template: &build_definition
  tags: [shared-ci-docker]
  stage: build
  variables:
    VUE_APP_TITLE: '{{ vue_app_title }}'
  only:
    - tags
    - merge_requests
    - master
  script:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci
    - npm run build
  artifacts:
    expire_in: 3 mos
    name: 'lck-front-${CI_COMMIT_REF_SLUG}'
    paths:
    - dist/

# storybook stage
storybook:build:
  tags: [shared-ci-docker]
  stage: storybook
  only:
    - merge_requests
    - master
  script:
    - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci
    - npm run storybook:build
  artifacts:
    expire_in: 1 week
    name: 'lck-front-storybook-${CI_COMMIT_REF_SLUG}'
    paths:
      - storybook-static

# lint & test stage
quality:
  image: buildkite/puppeteer
  tags: [shared-ci-docker]
  stage: lint-tests
  only:
    - merge_requests
    - master
  script:
    - npm ci
    - npm run lint
    - npm run test:unit -- --coverage --reporters=default
  dependencies:
    - storybook:build
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  artifacts:
    expire_in: 1 week
    name: 'lck-front-snapshots-${CI_COMMIT_REF_SLUG}'
    when: always
    paths:
    - tests/unit/__image_snapshots__
    reports:
      junit:
        - junit.xml

# Build stage
build:
  <<: *build_definition

# Deploy stage
deploy-vlog-staging:
  tags: [shared-ci-docker]
  dependencies:
    - build
  stage: deploy
  only:
    - merge_requests
  script:
    - cp public/assets/js/config-vlog-staging.js dist/assets/js/config.js
    - npx surge dist lck-vlog-staging-${CI_COMMIT_REF_SLUG}.surge.sh
  environment:
    name: review/lck-vlog-staging-${CI_COMMIT_REF_SLUG}
    url: http://lck-vlog-staging-${CI_COMMIT_REF_SLUG}.surge.sh
    on_stop: teardown-vlog-staging

deploy-storybook:
  tags: [shared-ci-docker]
  dependencies:
    - storybook:build
  stage: deploy
  only:
    - merge_requests
  script:
    - npx surge storybook-static lck-storybook-${CI_COMMIT_REF_SLUG}.surge.sh
  environment:
    name: review/lck-storybook-${CI_COMMIT_REF_SLUG}
    url: http://lck-storybook-${CI_COMMIT_REF_SLUG}.surge.sh
    on_stop: teardown-storybook

deploy-storybook-master:
  tags: [shared-ci-docker]
  dependencies:
    - storybook:build
  stage: deploy
  only:
    - master
  script:
    - npx surge storybook-static lck-storybook.surge.sh
  environment:
    name: review/lck-storybook
    url: http://lck-storybook.surge.sh

teardown-vlog-staging:
  tags: [shared-ci-docker]
  stage: deploy
  only:
    - merge_requests
  variables:
    GIT_STRATEGY: none
  script:
    - npx surge teardown lck-vlog-staging-${CI_COMMIT_REF_SLUG}.surge.sh
  when: manual
  environment:
    name: review/lck-vlog-staging-${CI_COMMIT_REF_SLUG}
    url: http://lck-vlog-staging-${CI_COMMIT_REF_SLUG}.surge.sh
    action: stop

teardown-storybook:
  tags: [shared-ci-docker]
  stage: deploy
  only:
    - merge_requests
  variables:
    GIT_STRATEGY: none
  script:
    - npx surge teardown lck-storybook-${CI_COMMIT_REF_SLUG}.surge.sh
  when: manual
  environment:
    name: review/lck-storybook-${CI_COMMIT_REF_SLUG}
    url: http://lck-storybook-${CI_COMMIT_REF_SLUG}.surge.sh
    action: stop
