version: '3'
services:
  postgres:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pouicpouic
    # restart: always
    volumes:
      - lck-db-data:/var/lib/postgresql/data
      - ./dumps:/dumps
    container_name: lck-api-db

  postgres-test:
    image: postgis/postgis:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pouicpouic
    # restart: always
    volumes:
      - ./dumps:/dumps
    container_name: lck-api-db-test

#  mailhog:
#    image: mailhog/mailhog:latest
#    environment:
#      MH_STORAGE: maildir
#      MH_MAILDIR_PATH: /home/mailhog
#    volumes:
#      - mailhog:/home/mailhog/
#    ports:
#      - 1025:1025
#      - 8025:8025

volumes:
  lck-db-data:
  mailhog:
