version: '3'
services:
  postgres:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pouicpouic
    # restart: always
    volumes:
      - lck-db-data:/var/lib/postgresql/data

  postgres-test:
    image: postgis/postgis:latest
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pouicpouic
    # restart: always

volumes:
  lck-db-data:
