# This docker-compose is for testing purpose only
# For a deployment, you'll need to set a mail server
# and security with helmet environment variables,
# maybe a nginx for serving front and reverse proxy to the api and the file storage.
version: '3'
services:

  lck-mail-next:
    image: mailhog/mailhog:latest
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
    volumes:
      - lck-mailhog-data:/home/mailhog/
    ports:
      - 1025:1025
      - 8025:8025
    container_name: lck-mail-next

  lck-db-next:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: locokit
      POSTGRES_USER: locokitmaster
      POSTGRES_PASSWORD: locokitMasterPassWORD
      TZ: 'UTC'
      PGTZ: 'UTC'
    # restart: always
    volumes:
      - lck-db-data:/var/lib/postgresql/data
    container_name: lck-db-next

  lck-pgadmin:
    image: dpage/pgadmin4:6
    environment:
      PGADMIN_DEFAULT_EMAIL: contact@locokit.io
      PGADMIN_DEFAULT_PASSWORD: locokit
    ports:
      - 8001:80
    volumes:
      - lck-pgadmin4-data:/var/lib/postgresql/data
      - ./dumps:/dumps
    container_name: lck-pgadmin-next


volumes:
  lck-mailhog-data:
  lck-db-data:
  lck-pgadmin4-data:
