# This docker-compose is for testing purpose only
# For a deployment, you'll need to set a mail server
# and security with helmet environment variables,
# maybe a nginx for serving front and reverse proxy to the api and the file storage.
version: '3'
services:

  lck-mail-next:
    image: mailhog/mailhog:latest
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
    volumes:
      - mailhog-next:/home/mailhog/
    ports:
      - "1025:1025"
      - "8025:8025"
    container_name: lck-mail-next

  lck-db-next:
    image: postgis/postgis:15-3.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: locokit
      POSTGRES_USER: locokitmaster
      POSTGRES_PASSWORD: locokitMasterPassWORD
      TZ: 'UTC'
      PGTZ: 'UTC'
    # restart: always
    volumes:
      - lck-db-next-data:/var/lib/postgresql/data
    container_name: lck-db-next

volumes:
  mailhog-next:
  lck-db-next-data:
