/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/account/profile': RouteRecordInfo<'/account/profile', '/account/profile', Record<never, never>, Record<never, never>>,
    '/account/profile/': RouteRecordInfo<'/account/profile/', '/account/profile', Record<never, never>, Record<never, never>>,
    '/account/profile/update-email': RouteRecordInfo<'/account/profile/update-email', '/account/profile/update-email', Record<never, never>, Record<never, never>>,
    '/account/profile/update-general': RouteRecordInfo<'/account/profile/update-general', '/account/profile/update-general', Record<never, never>, Record<never, never>>,
    '/account/profile/update-password': RouteRecordInfo<'/account/profile/update-password', '/account/profile/update-password', Record<never, never>, Record<never, never>>,
    '/account/sign-in': RouteRecordInfo<'/account/sign-in', '/account/sign-in', Record<never, never>, Record<never, never>>,
    '/admin': RouteRecordInfo<'/admin', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/groups': RouteRecordInfo<'/admin/groups', '/admin/groups', Record<never, never>, Record<never, never>>,
    '/admin/groups/': RouteRecordInfo<'/admin/groups/', '/admin/groups', Record<never, never>, Record<never, never>>,
    '/admin/groups/[id]': RouteRecordInfo<'/admin/groups/[id]', '/admin/groups/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/groups/create': RouteRecordInfo<'/admin/groups/create', '/admin/groups/create', Record<never, never>, Record<never, never>>,
    '/admin/users': RouteRecordInfo<'/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/admin/users/': RouteRecordInfo<'/admin/users/', '/admin/users', Record<never, never>, Record<never, never>>,
    '/admin/users/[id]': RouteRecordInfo<'/admin/users/[id]', '/admin/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/users/create': RouteRecordInfo<'/admin/users/create', '/admin/users/create', Record<never, never>, Record<never, never>>,
    '/w/': RouteRecordInfo<'/w/', '/w', Record<never, never>, Record<never, never>>,
    '/w/[wsslug]': RouteRecordInfo<'/w/[wsslug]', '/w/:wsslug', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin': RouteRecordInfo<'/w/[wsslug]/admin', '/w/:wsslug/admin', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/apps': RouteRecordInfo<'/w/[wsslug]/admin/apps', '/w/:wsslug/admin/apps', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/dashboards': RouteRecordInfo<'/w/[wsslug]/admin/dashboards', '/w/:wsslug/admin/dashboards', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/ds': RouteRecordInfo<'/w/[wsslug]/admin/ds', '/w/:wsslug/admin/ds', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/ds/[dsslug]': RouteRecordInfo<'/w/[wsslug]/admin/ds/[dsslug]', '/w/:wsslug/admin/ds/:dsslug', { wsslug: ParamValue<true>, dsslug: ParamValue<true> }, { wsslug: ParamValue<false>, dsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/ds/[dsslug]/t/[tslug]': RouteRecordInfo<'/w/[wsslug]/admin/ds/[dsslug]/t/[tslug]', '/w/:wsslug/admin/ds/:dsslug/t/:tslug', { wsslug: ParamValue<true>, dsslug: ParamValue<true>, tslug: ParamValue<true> }, { wsslug: ParamValue<false>, dsslug: ParamValue<false>, tslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/ds/[dsslug]/tables': RouteRecordInfo<'/w/[wsslug]/admin/ds/[dsslug]/tables', '/w/:wsslug/admin/ds/:dsslug/tables', { wsslug: ParamValue<true>, dsslug: ParamValue<true> }, { wsslug: ParamValue<false>, dsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/groups': RouteRecordInfo<'/w/[wsslug]/admin/groups', '/w/:wsslug/admin/groups', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/groups/[guuid]': RouteRecordInfo<'/w/[wsslug]/admin/groups/[guuid]', '/w/:wsslug/admin/groups/:guuid', { wsslug: ParamValue<true>, guuid: ParamValue<true> }, { wsslug: ParamValue<false>, guuid: ParamValue<false> }>,
    '/w/[wsslug]/admin/groups/create': RouteRecordInfo<'/w/[wsslug]/admin/groups/create', '/w/:wsslug/admin/groups/create', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/medias': RouteRecordInfo<'/w/[wsslug]/admin/medias', '/w/:wsslug/admin/medias', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/policies': RouteRecordInfo<'/w/[wsslug]/admin/policies', '/w/:wsslug/admin/policies', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/policies/[uuid]': RouteRecordInfo<'/w/[wsslug]/admin/policies/[uuid]', '/w/:wsslug/admin/policies/:uuid', { wsslug: ParamValue<true>, uuid: ParamValue<true> }, { wsslug: ParamValue<false>, uuid: ParamValue<false> }>,
    '/w/[wsslug]/admin/settings': RouteRecordInfo<'/w/[wsslug]/admin/settings', '/w/:wsslug/admin/settings', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/users': RouteRecordInfo<'/w/[wsslug]/admin/users', '/w/:wsslug/admin/users', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
    '/w/[wsslug]/admin/workflows': RouteRecordInfo<'/w/[wsslug]/admin/workflows', '/w/:wsslug/admin/workflows', { wsslug: ParamValue<true> }, { wsslug: ParamValue<false> }>,
  }
}
