/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PrimeAccordion: typeof import('primevue/accordion')['default']
    PrimeAccordionTab: typeof import('primevue/accordiontab')['default']
    PrimeAutoComplete: typeof import('primevue/autocomplete')['default']
    PrimeButton: typeof import('primevue/button')['default']
    PrimeCalendar: typeof import('primevue/calendar')['default']
    PrimeCheckbox: typeof import('primevue/checkbox')['default']
    PrimeConfirmDialog: typeof import('primevue/confirmdialog')['default']
    PrimeDropdown: typeof import('primevue/dropdown')['default']
    PrimeInputText: typeof import('primevue/inputtext')['default']
    PrimePaginator: typeof import('primevue/paginator')['default']
    PrimeTabPanel: typeof import('primevue/tabpanel')['default']
    PrimeTabView: typeof import('primevue/tabview')['default']
    PrimeTextarea: typeof import('primevue/textarea')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
