#
# This workflow build several docker images
# As it consumes a lot of resources (network, CPU, ...),
# we set the trigger to be manually dispatch
#
# see https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
#

name: Docker images workflow

on:
  workflow_dispatch:
  push:
    branches:
      - next

jobs:
  locokit-api-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64,linux/arm64/v8,linux/arm/v6,linux/arm/v7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: metapi
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            locokit/api
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Print GITHUB REF
        run: echo $GITHUB_REF
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push locokit/api
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./DockerfileARM32bits
          push: true
          tags: ${{ steps.metapi.outputs.tags }}
          target: locokit-api
          labels: ${{ steps.metapi.outputs.labels }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Docker meta
        id: metapp
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            locokit/app
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push locokit/app
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./DockerfileARM32bits
          push: true
          tags: ${{ steps.metapp.outputs.tags }}
          target: locokit-app
          labels: ${{ steps.metapp.outputs.labels }}
          platforms: ${{ matrix.platform }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
