name: Packages quality workflow

on:
  push:
    branches:
      - next
  pull_request:

jobs:

  ## Front part
  #  front-quality:
  #
  #    runs-on: ubuntu-latest
  #
  #    strategy:
  #      matrix:
  #        node-version: [ 18.x ]
  #
  #    defaults:
  #      run:
  #        working-directory: front
  #
  #
  #    steps:
  #      - uses: actions/checkout@v3
  #      - name: Setup node
  #        uses: actions/setup-node@v3
  #        with:
  #          node-version-file: '.nvmrc'


  front-translation:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/i18n

    steps:
      - uses: actions/checkout@v3
      - name: Run script to check keys in translation files
        run: |
          chmod +x ./compareKeyTranslation.sh
          ./compareKeyTranslation.sh
        shell: bash
