name: LocoKit CI

on:
  push:
    branches:
      - master
  pull_request:

  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:

  ## Front part
  front-quality:

    runs-on: ubuntu-latest

    container: buildkite/puppeteer

    defaults:
      run:
        working-directory: front

    # - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG != ""'

    steps:
      - uses: actions/checkout@v2
      - name: Upgrade NPM
        run: npm i -g npm@7
      - name: NPM Version
        run: npm -v
      - name: Go to Front folder
        run: cd front/
      - name: Install dependencies
        run: npm ci
      - name: Build storybook
        run: npm run storybook:build
      - name: Unit tests
        run: npm run test:unit -- --coverage --reporters=default
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lck-front-quality
          path: |
            front/tests/unit/__image_snapshots__
            front/storybook-static

  front-build:

    runs-on: ubuntu-latest

    container: node:16
    defaults:
      run:
        working-directory: front

    # needs: [front-quality]
    # - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_TAG != ""'

    env:
      VUE_APP_I18N_LOCALE: 'fr'
      VUE_APP_I18N_FALLBACK_LOCALE: 'fr'
      VUE_APP_TITLE: '{{ lck_app_title }}'
      VUE_APP_THEME: '{{ lck_app_theme }}'
    
    steps:
      - uses: actions/checkout@v2
      - name: NPM Version
        run: npm -v
      - name: Go to API folder
        run: cd front/
      - name: Install dependencies
        run: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm ci
      - name: Build front
        run: npm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lck-front
          path: |
            front/dist/


  ## API Part
  api-quality:

    runs-on: ubuntu-latest

    container: node:16

    defaults:
      run:
        working-directory: api

    env:
      LCK_PORT: 3030
      LCK_HOST: localhost
      LCK_DATABASE_URL_TEST: postgres://postgres:pouicpouic@lck-db:5432/postgres

      OBJECTION_DEBUG: 'false'
      NODE_ENV: test

      STORAGE_TYPE: fs
      STORAGE_PUBLIC_PATH: /storage
      STORAGE_FS_PATH: ../fs-storage
      STORAGE_S3_URL: http://lck-s3:9000
      STORAGE_S3_ACCESS_KEY: minio
      STORAGE_S3_SECRET_KEY: notsecret
      STORAGE_S3_PATH_STYLE: 1
      STORAGE_S3_SIGNATURE_VERSION: v4
      STORAGE_S3_DEFAULT_BUCKET: public

      NODE_OPTIONS: --max_old_space_size=4096

    services:
      lck-db:
        image: postgis/postgis:12-3.0
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pouicpouic

      lck-s3:
        image: minio/minio:latest
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: notsecret
        # options: server /data
    steps:
      - uses: actions/checkout@v2
      - name: NPM Version
        run: npm -v
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Unit tests
        run: npm test
        env:
          NODE_OPTIONS: --max_old_space_size=4096
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: api-quality-artifact
          path: |
            api/coverage

  api-build:
    runs-on: ubuntu-latest

    container: node:16

    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2
      - name: NPM Version
        run: npm -v
      - name: Install dependencies
        run: npm ci
      - name: Build API lib
        run: npm run compile
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: api-build-lib-artifact
          path: |
            api/lib

  ## Documentation part
  docs-build:
    runs-on: ubuntu-latest

    env:
      BASE_URL: '/lck-docs/'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build documentation
        run: npx vitepress build docs
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-build-artifact
          path: |
            docs/.vitepress/dist


  locokit-docker:
    runs-on: ubuntu-latest
    needs: [front-build, api-build, docs-build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: locokit/locokit:latest

# api-build-docker-tagged:
#   extends: .api-docker-template
#   rules:
#     - if: '$CI_COMMIT_TAG != ""'
#       when: manual
#   variables:
#     IMAGE_VERSION: "${CI_COMMIT_TAG}"
#   script:
#     - docker build --cache-from $IMAGE_NAME:latest --tag $IMAGE_NAME:$IMAGE_VERSION --tag $IMAGE_NAME:latest .
#     - docker push $IMAGE_NAME:$IMAGE_VERSION
#     - docker push $IMAGE_NAME:latest

