name: Docs CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BASE_URL: '/lck-docs/'

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build documentation
        run: npx vitepress build docs
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-build-artifact
          path: |
            docs/.vitepress/dist
