
pkg-glossary-lint:
  extends: .default-template
  stage: quality
  script:
    - npm ci
    - npm run lint --workspace=packages/glossary
  needs: []
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - when: manual
    - changes: 
      - packages/glossary/**.*
    - if: '$CI_COMMIT_TAG != ""'
      when: manual

pkg-glossary-build:
  extends: .default-template
  stage: build
  script:
    - npm ci
    - npm run build --workspace=packages/glossary
  artifacts:
    expire_in: 1 month
    when: always
    paths:
    - lib
  needs: ["pkg-glossary-lint"]
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - when: manual
    - changes: 
      - packages/glossary/**.*
    - if: '$CI_COMMIT_TAG != ""'
      when: manual

pkg-glossary-publish:
  extends: .default-template
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}">~/.npmrc
    - npm publish --workspace=packages/glossary
  needs: ["pkg-glossary-build"]
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - when: manual
    - changes: 
      - packages/glossary/**.*
    - if: '$CI_COMMIT_TAG != ""'
      when: manual