name: API CI

on:
  push:
  pull_request:

jobs:
  quality:

    runs-on: ubuntu-latest

    container: node:16

    env:
      LCK_PORT: 3030
      LCK_HOST: localhost
      LCK_DATABASE_URL_TEST: postgres://postgres:pouicpouic@lck-db:5432/postgres

      OBJECTION_DEBUG: 'false'
      NODE_ENV: test

      STORAGE_TYPE: fs
      STORAGE_PUBLIC_PATH: /storage
      STORAGE_FS_PATH: ../fs-storage
      STORAGE_S3_URL: http://lck-s3:9000
      STORAGE_S3_ACCESS_KEY: minio
      STORAGE_S3_SECRET_KEY: notsecret
      STORAGE_S3_PATH_STYLE: 1
      STORAGE_S3_SIGNATURE_VERSION: v4
      STORAGE_S3_DEFAULT_BUCKET: public

    services:
      lck-db:
        image: postgis/postgis:12-3.0
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pouicpouic

      lck-s3:
        image: minio/minio:latest
        env:
          MINIO_ACCESS_KEY: minio
          MINIO_SECRET_KEY: notsecret

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci --workspace=api && cp -r api/patch/** api/node_modules/
      - name: Lint code
        run: npm run lint --workspace=api
      - name: Unit tests
        run: npm test --workspace=api
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: api-quality-artifact
          path: |
            api/coverage

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --workspace=api && cp -r api/patch/** api/node_modules/
      - name: Unit tests
        run: npm run compile --workspace=api
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: api-build-artifact
          path: |
            api/lib
